import { z } from 'zod'
import { CommandSchemaRegistry } from './commands.js'
import {
  MessageSchema,
  ProjectSchema,
  ProviderProfileSchema,
  RunSchema,
  TurnExecutionSchema,
  SessionSchema,
  SkillManifestSchema,
  ToolCallSchema,
  ToolSpecSchema,
  WorkspaceEntrySchema,
  WorkspaceIndexSnapshotSchema,
  WorkspaceReadResultSchema,
  WorkspaceWriteResultSchema,
  ChangedFileSchema,
  ToolOutputSchema,
  FileWriteResultSchema,
  FileEditResultSchema,
  FileDeleteResultSchema,
  FileMoveResultSchema,
  FileMkdirResultSchema,
  GitChangeEntrySchema,
  AssetRefSchema,
  ResourceLinkSchema,
  ArtifactSchema,
  QueueEntrySchema,
  AgentSettingsSchema,
  McpServerSchema,
  McpToolSchema,
  PermissionPresetSchema,
  ApprovalOverrideSchema,
  SandboxPolicySchema,
} from './entities.js'
import {
  ApprovalRiskSchema,
  ApprovalSubjectSchema,
  ApprovalChoiceSchema,
  ApprovalContextSchema,
  ApprovalGrantV2Schema,
  ShellInterpreterSchema,
  ShellExecuteParamsSchema,
  DangerProviderSchema,
  DangerCapabilitySchema,
  DangerAccessLeaseSchema,
  DangerRevokeReasonSchema,
} from './permissions.js'
import { RuntimeErrorSchema } from './errors.js'
import { JsonRpcMessageSchema } from './jsonrpc.js'
import { RuntimeEventSchema } from './events.js'
import { PluginPackageManifestSchema, PluginRecordSchema } from './plugins.js'

function toJSONSchema(name: string, schema: z.ZodType): [string, unknown] {
  return [name, z.toJSONSchema(schema)]
}

export const jsonSchemas: Readonly<Record<string, unknown>> = Object.freeze(
  Object.fromEntries([
    toJSONSchema('JsonRpcMessage', JsonRpcMessageSchema),
    toJSONSchema('Project', ProjectSchema),
    toJSONSchema('Session', SessionSchema),
    toJSONSchema('Message', MessageSchema),
    toJSONSchema('Run', RunSchema),
    toJSONSchema('TurnExecution', TurnExecutionSchema),
    toJSONSchema('ToolCall', ToolCallSchema),
    toJSONSchema('ToolSpec', ToolSpecSchema),
    toJSONSchema('SkillManifest', SkillManifestSchema),
    toJSONSchema('PluginPackageManifest', PluginPackageManifestSchema),
    toJSONSchema('PluginRecord', PluginRecordSchema),
    toJSONSchema('ProviderProfile', ProviderProfileSchema),
    toJSONSchema('WorkspaceEntry', WorkspaceEntrySchema),
    toJSONSchema('WorkspaceIndexSnapshot', WorkspaceIndexSnapshotSchema),
    toJSONSchema('WorkspaceReadResult', WorkspaceReadResultSchema),
    toJSONSchema('WorkspaceWriteResult', WorkspaceWriteResultSchema),
    toJSONSchema('ChangedFile', ChangedFileSchema),
    toJSONSchema('ToolOutput', ToolOutputSchema),
    toJSONSchema('FileWriteResult', FileWriteResultSchema),
    toJSONSchema('FileEditResult', FileEditResultSchema),
    toJSONSchema('FileDeleteResult', FileDeleteResultSchema),
    toJSONSchema('FileMoveResult', FileMoveResultSchema),
    toJSONSchema('FileMkdirResult', FileMkdirResultSchema),
    toJSONSchema('GitChangeEntry', GitChangeEntrySchema),
    toJSONSchema('AssetRef', AssetRefSchema),
    toJSONSchema('ResourceLink', ResourceLinkSchema),
    toJSONSchema('Artifact', ArtifactSchema),
    toJSONSchema('QueueEntry', QueueEntrySchema),
    toJSONSchema('AgentSettings', AgentSettingsSchema),
    toJSONSchema('McpServer', McpServerSchema),
    toJSONSchema('McpTool', McpToolSchema),
    toJSONSchema('PermissionPreset', PermissionPresetSchema),
    toJSONSchema('ApprovalOverride', ApprovalOverrideSchema),
    toJSONSchema('SandboxPolicy', SandboxPolicySchema),
    toJSONSchema('ApprovalRisk', ApprovalRiskSchema),
    toJSONSchema('ApprovalSubject', ApprovalSubjectSchema),
    toJSONSchema('ApprovalChoice', ApprovalChoiceSchema),
    toJSONSchema('ApprovalContext', ApprovalContextSchema),
    toJSONSchema('ApprovalGrantV2', ApprovalGrantV2Schema),
    toJSONSchema('ShellInterpreter', ShellInterpreterSchema),
    toJSONSchema('ShellExecuteParams', ShellExecuteParamsSchema),
    toJSONSchema('DangerProvider', DangerProviderSchema),
    toJSONSchema('DangerCapability', DangerCapabilitySchema),
    toJSONSchema('DangerAccessLease', DangerAccessLeaseSchema),
    toJSONSchema('DangerRevokeReason', DangerRevokeReasonSchema),
    toJSONSchema('RuntimeError', RuntimeErrorSchema),
    toJSONSchema('RuntimeEvent', RuntimeEventSchema),
    ...Object.entries(CommandSchemaRegistry).flatMap(([method, entry]) => [
      toJSONSchema(`${method}.params`, entry.params),
      toJSONSchema(`${method}.result`, entry.result),
    ]),
  ]),
)
